apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: thirdstravel-com-tls
spec:
  secretName: thirdstravel-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: thirdstravel.com
  dnsNames:
    - thirdstravel.com
    - www.thirdstravel.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - thirdstravel.com
          - www.thirdstravel.com
